# Generated by Django 6.0 on 2026-02-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='class_fk',
            new_name='gym_class',
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(help_text='Price in BHD'),
        ),
    ]
