# Generated by Django 6.0 on 2026-02-02 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_class_fk_workoutplan_gym_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='GymClass',
        ),
    ]
