# Generated by Django 6.0 on 2026-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_class_gymclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='speciality',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('member', 'Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, null=True),
        ),
    ]
